# http://docs.travis-ci.com/user/languages/android/
# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI

language: android

# It's needed for Gradle 3+
jdk: oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22

before_install:
  - chmod +x gradlew  # Fix wrong file rights (useful if developing in windows)
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"

script:
  - ./gradlew build connectedCheck
  #- ./gradlew clean assembleRelease

after_failure: "cat $TRAVIS_BUILD_DIR/Reedy/build/outputs/lint-results-debug.xml"
