# http://docs.travis-ci.com/user/languages/android/
# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI

language: android

# It's needed for Gradle 3+
jdk: oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22

before_install:
  - chmod +x gradlew  # Fix wrong file rights (useful if developing in windows)
  - echo "Travis branch is $TRAVIS_BRANCH ($TRAVIS_EVENT_TYPE)"
  - echo "Travis branch is in pull request $TRAVIS_PULL_REQUEST (from $TRAVIS_PULL_REQUEST_BRANCH)"

script:
  - ./gradlew build connectedCheck
  #- ./gradlew clean assembleRelease

after_failure: "cat $TRAVIS_BUILD_DIR/Reedy/build/outputs/lint-results-debug.xml"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4285f611e4aca62773fc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
